import type { MetafieldOwnerType, ValueType } from "./types"

export const METAFIELD_LIBRARY_VERTICALS = ["skincare", "fashion"] as const

export type MetafieldLibraryVertical = (typeof METAFIELD_LIBRARY_VERTICALS)[number]

export const METAFIELD_LIBRARY_NAMESPACE = "mercflow_library" as const

export const METAFIELD_ACTIVATED_NAMESPACE = "mercflow_standard" as const

export type StandardLibrarySeed = {
  id: string
  vertical: MetafieldLibraryVertical
  owner_type: MetafieldOwnerType
  key: string
  name: string
  description: string | null
  type: ValueType
  is_primary: boolean
  pinned_position: number | null
}

export const STANDARD_LIBRARY_SEEDS: StandardLibrarySeed[] = [
  {
    id: "mfd_lib_skincare_material",
    vertical: "skincare",
    owner_type: "product",
    key: "material",
    name: "Materiale",
    description: "Primary material or base composition of the product.",
    type: "single_line_text",
    is_primary: true,
    pinned_position: 1,
  },
  {
    id: "mfd_lib_skincare_age_group",
    vertical: "skincare",
    owner_type: "product",
    key: "age_group",
    name: "Aldersgruppe",
    description: "Recommended age group for the product.",
    type: "list.single_line_text",
    is_primary: true,
    pinned_position: 2,
  },
  {
    id: "mfd_lib_skincare_cosmetic_function",
    vertical: "skincare",
    owner_type: "product",
    key: "cosmetic_function",
    name: "Kosmetisk funktion",
    description: "Primary cosmetic function or benefit.",
    type: "list.single_line_text",
    is_primary: true,
    pinned_position: 3,
  },
  {
    id: "mfd_lib_skincare_package_type",
    vertical: "skincare",
    owner_type: "product",
    key: "package_type",
    name: "Pakketype",
    description: "Packaging format such as tube, jar, or pump.",
    type: "single_line_text",
    is_primary: true,
    pinned_position: 4,
  },
  {
    id: "mfd_lib_skincare_target_gender",
    vertical: "skincare",
    owner_type: "product",
    key: "target_gender",
    name: "Målkøn",
    description: "Intended gender audience for the product.",
    type: "single_line_text",
    is_primary: true,
    pinned_position: 5,
  },
  {
    id: "mfd_lib_skincare_spf_level",
    vertical: "skincare",
    owner_type: "product",
    key: "spf_level",
    name: "SPF-niveau",
    description: "Sun protection factor rating.",
    type: "number_integer",
    is_primary: false,
    pinned_position: 10,
  },
  {
    id: "mfd_lib_skincare_scent",
    vertical: "skincare",
    owner_type: "product",
    key: "scent",
    name: "Duft",
    description: "Fragrance profile or scent notes.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 11,
  },
  {
    id: "mfd_lib_skincare_skin_type",
    vertical: "skincare",
    owner_type: "product",
    key: "skin_type",
    name: "Velegnet til hudtype",
    description: "Skin types the product is suitable for.",
    type: "list.single_line_text",
    is_primary: false,
    pinned_position: 12,
  },
  {
    id: "mfd_lib_skincare_dispenser_type",
    vertical: "skincare",
    owner_type: "product",
    key: "dispenser_type",
    name: "Dispensertype",
    description: "How the product is dispensed.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 13,
  },
  {
    id: "mfd_lib_skincare_ingredient_origin",
    vertical: "skincare",
    owner_type: "product",
    key: "ingredient_origin",
    name: "Ingrediensoprindelse",
    description: "Origin or sourcing of key ingredients.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 14,
  },
  {
    id: "mfd_lib_skincare_active_ingredients",
    vertical: "skincare",
    owner_type: "product",
    key: "active_ingredients",
    name: "Aktive ingredienser",
    description: "Active ingredient list or INCI highlights.",
    type: "multi_line_text",
    is_primary: false,
    pinned_position: 15,
  },
  {
    id: "mfd_lib_skincare_volume",
    vertical: "skincare",
    owner_type: "product",
    key: "volume",
    name: "Volumen",
    description: "Net volume or weight of the product.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 16,
  },
  {
    id: "mfd_lib_skincare_application_method",
    vertical: "skincare",
    owner_type: "product",
    key: "application_method",
    name: "Anvendelse",
    description: "How to apply or use the product.",
    type: "multi_line_text",
    is_primary: false,
    pinned_position: 17,
  },
  {
    id: "mfd_lib_skincare_fragrance_content",
    vertical: "skincare",
    owner_type: "product",
    key: "fragrance_content",
    name: "Indhold af parfume",
    description: "Fragrance content classification.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 18,
  },
  {
    id: "mfd_lib_skincare_uv_protection",
    vertical: "skincare",
    owner_type: "product",
    key: "uv_protection",
    name: "UV-beskyttelse",
    description: "Whether the product provides UV protection.",
    type: "boolean",
    is_primary: false,
    pinned_position: 19,
  },
  {
    id: "mfd_lib_skincare_vegan",
    vertical: "skincare",
    owner_type: "product",
    key: "vegan",
    name: "Vegansk",
    description: "Whether the product is vegan.",
    type: "boolean",
    is_primary: false,
    pinned_position: 20,
  },
  {
    id: "mfd_lib_fashion_material",
    vertical: "fashion",
    owner_type: "product",
    key: "material",
    name: "Materiale",
    description: "Primary fabric or material composition.",
    type: "single_line_text",
    is_primary: true,
    pinned_position: 1,
  },
  {
    id: "mfd_lib_fashion_fit_type",
    vertical: "fashion",
    owner_type: "product",
    key: "fit_type",
    name: "Pasform",
    description: "Garment fit such as slim, regular, or relaxed.",
    type: "single_line_text",
    is_primary: true,
    pinned_position: 2,
  },
  {
    id: "mfd_lib_fashion_target_audience",
    vertical: "fashion",
    owner_type: "product",
    key: "target_audience",
    name: "Målgruppe",
    description: "Intended audience or demographic.",
    type: "single_line_text",
    is_primary: true,
    pinned_position: 3,
  },
  {
    id: "mfd_lib_fashion_care_instructions",
    vertical: "fashion",
    owner_type: "product",
    key: "wash_instructions",
    name: "Plejeinstruktioner",
    description: "Washing and care instructions.",
    type: "multi_line_text",
    is_primary: true,
    pinned_position: 4,
  },
  {
    id: "mfd_lib_fashion_season",
    vertical: "fashion",
    owner_type: "product",
    key: "season",
    name: "Sæson",
    description: "Seasonal collection or wear period.",
    type: "list.single_line_text",
    is_primary: true,
    pinned_position: 5,
  },
  {
    id: "mfd_lib_fashion_fabric_type",
    vertical: "fashion",
    owner_type: "product",
    key: "fabric_type",
    name: "Stoftype",
    description: "Fabric construction such as knit or woven.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 10,
  },
  {
    id: "mfd_lib_fashion_sleeve_length",
    vertical: "fashion",
    owner_type: "product",
    key: "sleeve_length",
    name: "Ærmelængde",
    description: "Sleeve length style.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 11,
  },
  {
    id: "mfd_lib_fashion_neckline",
    vertical: "fashion",
    owner_type: "product",
    key: "neckline",
    name: "Halsudskæring",
    description: "Neckline style.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 12,
  },
  {
    id: "mfd_lib_fashion_pattern",
    vertical: "fashion",
    owner_type: "product",
    key: "pattern",
    name: "Mønster",
    description: "Pattern such as solid, stripe, or check.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 13,
  },
  {
    id: "mfd_lib_fashion_closure_type",
    vertical: "fashion",
    owner_type: "product",
    key: "closure_type",
    name: "Lukning",
    description: "Closure mechanism such as zip or buttons.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 14,
  },
  {
    id: "mfd_lib_fashion_garment_length",
    vertical: "fashion",
    owner_type: "product",
    key: "garment_length",
    name: "Længde",
    description: "Garment length such as cropped or full length.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 15,
  },
  {
    id: "mfd_lib_fashion_stretch_level",
    vertical: "fashion",
    owner_type: "product",
    key: "stretch_level",
    name: "Strækbarhed",
    description: "Stretch or elasticity level.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 16,
  },
  {
    id: "mfd_lib_fashion_lined",
    vertical: "fashion",
    owner_type: "product",
    key: "lined",
    name: "Foret",
    description: "Whether the garment is lined.",
    type: "boolean",
    is_primary: false,
    pinned_position: 17,
  },
  {
    id: "mfd_lib_fashion_sustainable",
    vertical: "fashion",
    owner_type: "product",
    key: "sustainable",
    name: "Bæredygtig",
    description: "Whether the product is marketed as sustainable.",
    type: "boolean",
    is_primary: false,
    pinned_position: 18,
  },
  {
    id: "mfd_lib_fashion_country_of_origin",
    vertical: "fashion",
    owner_type: "product",
    key: "country_of_origin",
    name: "Oprindelsesland",
    description: "Country of manufacture or origin.",
    type: "single_line_text",
    is_primary: false,
    pinned_position: 19,
  },
]

export function seedValidations(vertical: MetafieldLibraryVertical): Record<string, unknown> {
  return { vertical }
}

export function readVerticalFromValidations(
  validations: Record<string, unknown> | null
): MetafieldLibraryVertical | null {
  if (!validations || typeof validations.vertical !== "string") {
    return null
  }
  const vertical = validations.vertical
  if (vertical === "skincare" || vertical === "fashion") {
    return vertical
  }
  return null
}
