#!/usr/bin/env bash
# Local Shipmondo label E2E — sync admin-ui env + optional seed.
# Usage (from repo root):
#   ./scripts/shipmondo-e2e-dev.sh          # refresh admin-ui .env.local only
#   ./scripts/shipmondo-e2e-dev.sh --seed   # also run seed-shipmondo-e2e.ts
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_DIR="$ROOT/apps/backend"
ADMIN_ENV_LOCAL="$ROOT/packages/admin-ui/.env.local"
BACKEND_URL="${MEDUSA_BACKEND_URL:-http://localhost:9000}"
ADMIN_EMAIL="${E2E_ADMIN_EMAIL:-admin@mercflow.local}"
ADMIN_PASSWORD="${E2E_ADMIN_PASSWORD:-}"
RUN_SEED=false

for arg in "$@"; do
  case "$arg" in
    --seed) RUN_SEED=true ;;
    -h|--help)
      echo "Usage: $0 [--seed]"
      echo "  Refreshes packages/admin-ui/.env.local (backend URL, bearer JWT, store id)."
      echo "  --seed  Runs apps/backend seed-shipmondo-e2e.ts (needs Shipmondo env in apps/backend/.env)."
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 1
      ;;
  esac
done

if [[ -f "$BACKEND_DIR/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$BACKEND_DIR/.env"
  set +a
fi

STORE_ID="${MERCFLOW_DEFAULT_STORE_ID:-}"
if [[ -z "$STORE_ID" ]]; then
  echo "WARN: MERCFLOW_DEFAULT_STORE_ID is not set in apps/backend/.env — order notes need VITE_MERCFLOW_DEFAULT_STORE_ID." >&2
fi

echo "Fetching admin JWT from ${BACKEND_URL} …"
TOKEN_RESPONSE="$(curl -sf -X POST "${BACKEND_URL}/auth/user/emailpass" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}" 2>/dev/null || true)"

if [[ -z "$TOKEN_RESPONSE" ]]; then
  echo "ERROR: Could not reach ${BACKEND_URL}. Start backend first: pnpm dev:backend" >&2
  exit 1
fi

TOKEN="$(printf '%s' "$TOKEN_RESPONSE" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("token",""))' 2>/dev/null || true)"
if [[ -z "$ADMIN_PASSWORD" ]]; then
  echo "ERROR: Set E2E_ADMIN_PASSWORD in apps/backend/.env (or export) before running setup." >&2
  exit 1
fi

if [[ -z "$TOKEN" ]]; then
  echo "ERROR: Login failed for ${ADMIN_EMAIL}. Response: ${TOKEN_RESPONSE}" >&2
  exit 1
fi

mkdir -p "$(dirname "$ADMIN_ENV_LOCAL")"
cat >"$ADMIN_ENV_LOCAL" <<EOF
# Generated by scripts/shipmondo-e2e-dev.sh — safe to regenerate.
VITE_MEDUSA_ADMIN_BACKEND_URL=${BACKEND_URL}
VITE_MEDUSA_ADMIN_BEARER_TOKEN=${TOKEN}
EOF

if [[ -n "$STORE_ID" ]]; then
  echo "VITE_MERCFLOW_DEFAULT_STORE_ID=${STORE_ID}" >>"$ADMIN_ENV_LOCAL"
fi

echo "Wrote ${ADMIN_ENV_LOCAL}"

if [[ "$RUN_SEED" == true ]]; then
  if [[ -z "${SHIPMONDO_API_USER:-}" || -z "${SHIPMONDO_API_KEY:-}" ]]; then
    echo "ERROR: Set SHIPMONDO_API_USER and SHIPMONDO_API_KEY in apps/backend/.env before --seed." >&2
    exit 1
  fi
  echo "Running Shipmondo E2E seed …"
  (
    cd "$BACKEND_DIR"
    SHIPMONDO_SANDBOX="${SHIPMONDO_SANDBOX:-true}" \
      pnpm exec medusa exec ./src/scripts/seed-shipmondo-e2e.ts
  )
fi

echo ""
echo "Next:"
echo "  1. pnpm dev:backend          (if not already running)"
echo "  2. pnpm --filter @mercflow/admin-ui dev"
echo "  3. Open http://localhost:5173/orders/order_<id> and use Generate label"
